zsol/py.wtf

- www/components/ModuleListSidebar.tsx
- www/pages/index.tsx
* #14
* #13
* #12
* __->__ #11
Without this, each click triggered a page reload. Now we do smart NextJS
things instead.
> [chore] Use next/link in ModuleListSidebar

- www/components/Class.tsx
- www/components/Intersperse.tsx
- www/components/ModuleListSidebar.tsx
- www/pages/[...pkg].tsx
* #14
* #13
* __->__ #12
* #11
* The duplicate variables are weird, probably problems in the indexer;
whatevs, shouldn't cause warnings on the frontend.
* Duplicate methods are valid because overloading; I failed to find a
stable ID, so just used the `index`, acknowledging that this is a bad
practice
> [chore] Fix some "duplicate key" warnings

- www/next.config.js
* __->__ #14
* #13
* #12
* #11
Before this change, we'd get lots of warnings about the data in
`getStaticProps` being too large
(https://nextjs.org/docs/messages/large-page-data). After thinking about
it a bit: documentation for a module is sometimes going to be large,
that's life. If / once we refactor the page structure this may get
better, but even then, documentation for a _class_ can be big. And
that's OK.
> Increased largePageDataBytes threshold

- .gitignore
- README.md
- publish.sh
- www/components/Docs/Module.tsx
- www/components/FetchPackage.tsx
- www/components/Sidebar/ModuleList.tsx
- www/lib/docs.ts
- www/lib/url.ts
- www/package-lock.json
- www/package.json
- www/pages/[pkg].tsx
- www/pages/[pkg]/[mod].tsx
- www/pages/[pkg]/[mod]/[symbol].tsx
- www/pages/index.tsx
Generating static pages for each symbol is a no-go; way too many, way
too big content. Let's "just" request the JSON from the client, and
render on the client.
* Fetching (including caching) with https://swr.vercel.app/, as
recommended by Next.js
* Updated `README.md` (and created `.gitkeep`) to store devenv index in
`www/public`, so that it gets served at the same URL as in prod
> Switch to client-side rendering

- py_wtf/indexer.py
- py_wtf/types.py
- test_fixtures/project-alpha/alpha/__init__.py
- www/lib/docs.ts
Explicitly exported symbols are collected into the `Module`'s `exports` field. This contains a list of fully qualified names for now, but we might want to switch to a smarter representation (maybe something like what's described in #8).
See https://docs.python.org/3/tutorial/modules.html#importing-from-a-package for how `__all__` works.
Closes #7
> feat: gather explicitly exported symbols

- py_wtf/indexer.py
Packages are represented by directories with `__init__.py` in them. This `__init__.py` is mapped to a module that's named exactly like the package.
Fixes #9
> feat: handle names of packages

- www/components/Docs/Function.tsx
- www/components/highlight.tsx
Yesterday's styling refactor broke the function signature display, removing the `:` before the type of the parameters and adding an extra space before the return arrow. This PR fixes it, making the display great again:
> Fixed the function signature display

- py_wtf/cli/__init__.py
- py_wtf/indexer/pypi.py
- py_wtf/repository.py
- py_wtf/types.py
- tests/test_repository.py
* #70
* #67
* #65
* #64
* #63
* #62
* __->__ #58
This acts as a cache layer between the indexer and the filesystem. In the future, the
indexer will ask for a project's dependencies from here for cross-referencing purposes.
> feat: add a project repository to the indexer

- py_wtf/indexer/pypi.py
- tests/indexer/test_pypi.py
* #70
* #67
* #65
* #64
* #63
* __->__ #62
* #58
While indexing projects, any dependency that has a marker like `extra == 'foo'` should be skipped. These markers can easily cause circular dependencies amongst projects.
> fix: dont include deps with markers

- py_wtf/cli/__init__.py
- py_wtf/indexer/file.py
- py_wtf/indexer/pypi.py
- py_wtf/repository.py
- py_wtf/types.py
- pyproject.toml
- tests/indexer/test_file.py
- tests/test_repository.py
* #70
* #67
* #65
* __->__ #64
* #63
* #62
* #58
dataclasses_json was silently failing to support NewTypes and Iterables. cattrs also doesn't support them yet, but is at least loud about them.
> chore: replace dataclasses_json with cattrs

- py_wtf/indexer/file.py
- py_wtf/indexer/pypi.py
- py_wtf/repository.py
- py_wtf/types.py
- tests/indexer/test_file.py
- tests/indexer/test_pypi.py
* #70
* #67
* __->__ #65
* #64
* #63
* #62
* #58
Previously `Module.exports` was just a simple list of names. Now it's a (projectname, fqname) tuple, where `projectname` is the name of the project `fqname` is defined in, or `None` if the indexer can't find it. This can be in two cases:
1. When `fqname` is defined in the same project as the module is in
2. When `fqname` comes from a project that isn't indexed: a standard library, an optional dependency (we only index required deps), or some other indexer error
> BREAKING CHANGE: link module exports to the project they come from

- www/components/FetchProject.tsx
- www/components/PageLayout.tsx
- www/components/SPA/ModulePage.tsx
- www/components/SPA/ProjectPage.tsx
- www/components/SPA/SymbolPage.tsx
- www/components/core/layout/ContentWithSidebar.tsx
- www/components/core/layout/FullPageBackground.tsx
- www/components/core/theme/theme.ts
- www/pages/_spa.tsx
- www/pages/index.tsx
- www/types/emotion.d.ts
- Added a `PageLayout` component that takes care of fixed placement headers and footers.
- Wrapped all top level pages into this component
- Magic 🌟 
Index looks:
> Let there be headers and footers!

- py_wtf/indexer/pypi.py
* __->__ #92
* #89
* #88
* #90
Handle the case when `pypi_info` explicitly has a `project_urls` field but it's set to `null` in the json.
Like for example for https://pypi.org/pypi/click-didyoumean/json
> fix: handle explicit null project_urls value

- www/components/Docs/Function.tsx
- www/components/Docs/Variable.tsx
- www/components/highlight.tsx
Also sanitized the syntax highlight theme a bit while we're at it.
But uhh... all the defaults seem to be `...` at the moment?
Closes #74
> Render function parameter default values

- www/__tests__/function.test.tsx
- www/lib/url.ts
* #114
* __->__ #113
* #112
When an xref's project field is `__std__`, the frontend now displays a link to docs.python.org.
Some caveats in this implementation:
- Only the latest version of Python 3 docs is shown.
- Links to class fields (methods, variables) are broken.
Fixes #99.
> feat: Show stdlib xrefs as links to official docs

- www/__tests__/index.test.tsx
- www/components/Docs/SymbolLinkTable.tsx
- www/components/Header.tsx
- www/components/PageLayout.tsx
- www/components/Sidebar/Sidebar.tsx
- www/components/core/Search.tsx
- www/components/core/navigation/Link.tsx
- www/components/core/theme/theme.ts
- www/lib/docs.ts
- www/lib/searchDescriptor.ts
- www/pages/index.tsx
- www/types/emotion.d.ts
* #124
* __->__ #123
* #122
* #121
Instead of listing all the projects, the index page now contains:
- a search bar, which searches in all known project names
- the latest indexed projects and their summaries
- the most popular projects in the index and their summaries
- the timestamp of the index
Closes #73.
Demo video:
https://user-images.githubusercontent.com/66740/188329712-fc22e5aa-ae8a-4afb-bf68-52ed9750662e.mp4
> feat: Redesign index page

- py_wtf/indexer/documentation.py
- tests/indexer/test_documentation.py
Specialize the built-in markdownit renderer to:
1. stop emitting `{eval-rst}` directives which aren't supported by the browser-side myst rendering
2. stop using the deprecated `rawsource` attribute in `field_list` nodes, which is broken. This should make us properly emit `:param foo:` markups which are extremely common.
| Before | After|
|--------|--------|
| ![image](https://github.com/zsol/py.wtf/assets/66740/f408b190-a35d-4834-a9d5-f6709ef59173) | ![image](https://github.com/zsol/py.wtf/assets/66740/79726124-dbf5-485b-8cf2-dd97d9286299) |
| ![image](https://github.com/zsol/py.wtf/assets/66740/1bc230a0-de63-4992-ab5f-4c598d708981) | ![image](https://github.com/zsol/py.wtf/assets/66740/cf37bdd7-8b88-46e0-ba5d-6ca8cb4506b3) |
> feat: Fix rendering of a unknown RST directives

- www/components/core/Search.tsx
- www/lib/searchDescriptor.ts
- www/pages/index.tsx
feat: search only in local name
Only search in the last part of the fully qualified name of symbols.
Example (from the `packaging` project):
> feat: search only in local name

- www/components/core/Search.tsx
fix(search): don't display fqname if doesn't exist
This happens on the main page when fuzzy search is used for projects.
> fix(search): don't display fqname if doesn't exist

- www/components/core/Search.tsx
search: Add keyboard navigation to results
After searching for a string, the user can navigate results by pressing up/down arrows.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zsol/py.wtf/pull/167).
* #168
* __->__ #167
> search: Add keyboard navigation to results

- .pre-commit-config.yaml
- py_wtf/cli/__init__.py
- py_wtf/indexer/file.py
- py_wtf/indexer/pypi.py
- py_wtf/logging.py
- py_wtf/repository.py
- pyproject.toml
- requirements.txt
- tests/indexer/test_file.py
Add more logging
Add more verbose `logging` logs, as well as a new `--trace` flag to dump chrome traces powered by `keke`.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zsol/py.wtf/pull/172).
* #174
* #173
* __->__ #172
> Add more logging

- py_wtf/cli/__init__.py
To stay within quota, it now has just under 30 days of data, so the filename has been updated. Both will be available for a while. See https://github.com/hugovk/top-pypi-packages/pull/46.
> Update top-pypi-packages filename
