www/components/Class.tsx, www/components/Function.tsx, www/components/Intersperse.tsx, www/components/Variable.tsx, www/components/highlight.tsx, www/pages/[...pkg].tsx
Note that the page is rapidly becoming hard to navigate. I'll file a few issues to track various aspects of that. This PR is more about getting the content in there.
=> Render docs for classes

www/components/Package.tsx, www/pages/[...pkg].tsx
* #14
* __->__ #13
* #12
* #11
=> [refactor] Moved Package component out of [...pkg].tsx

.gitignore
* #19
* #18
* #17
* __->__ #16
=> chore: Add vscode settings to gitignore

py_wtf/cli/__init__.py
* #19
* #18
* __->__ #17
* #16
=> feat: Fetch package metadata

py_wtf/cli/__init__.py
* #19
* __->__ #18
* #17
* #16
=> feat: Add command for indexing a local directory

py_wtf/cli/__init__.py
=> Zsol's magic to make the indexer run on Mac

py_wtf/cli/__init__.py, pyproject.toml
* #48
* #47
* #46
* __->__ #45
=> Parse package requirements properly

py_wtf/cli/__init__.py, py_wtf/types.py
* #48
* #47
* __->__ #46
* #45
=> chore: move PkgInfo to types.py and rename to ProjectMetadata

py_wtf/cli/__init__.py, py_wtf/types.py, www/components/Sidebar/Sidebar.tsx, www/lib/docs.ts, www/pages/index.tsx
* #48
* __->__ #47
* #46
* #45
=> chore: expose metadata to www

py_wtf/cli/__init__.py, py_wtf/indexer/__init__.py, py_wtf/indexer/file.py, py_wtf/indexer/pypi.py
* #56
* #55
* #54
* #53
* __->__ #52
=> chore: refactor indexer components into their own package

.pre-commit-config.yaml, py_wtf/indexer/file.py, py_wtf/types.py, pyproject.toml
* #56
* #55
* #54
* __->__ #53
* #52
=> chore: add mypy for type checking python

www/.prettierrc.json
* #56
* #55
* __->__ #54
* #53
* #52
=> chore: tell prettier to preserve line endings

.gitignore, .pre-commit-config.yaml, py_wtf/indexer/file.py, tests/__init__.py, tests/indexer/test_file.py, tests/indexer/test_pypi.py
* #56
* __->__ #55
* #54
* #53
* #52
=> chore: add unit tests for indexer parts

.github/workflows/indexer-tests.yml
* __->__ #56
* #55
* #54
* #53
* #52
=> chore: add GHA action for python tests

test_fixtures/project-alpha/project.json, www/components/Sidebar/Sidebar.tsx
=> feat: Display project website and docs

py_wtf/cli/__init__.py, py_wtf/indexer/pypi.py, tests/conftest.py
* #70
* #67
* #65
* #64
* __->__ #63
* #62
* #58
=> feat: index a project's dependencies too

py_wtf/cli/__init__.py, test_fixtures/project-beta/beta/__init__.py, test_fixtures/project-beta/project.json
* #70
* __->__ #67
* #65
* #64
* #63
* #62
* #58
=> chore: Add test fixture with cross-project export

.pre-commit-config.yaml
* __->__ #70
* #67
* #65
* #64
* #63
* #62
* #58
=> chore: always regenerate test index files

tests/test_types.py
=> chore: add roundtrip serialization tests

py_wtf/indexer/annotation.py, py_wtf/indexer/file.py, py_wtf/types.py, tests/indexer/test_annotation.py
=> feat: Emit rich type annotations from the indexer

www/__tests__/class.test.tsx, www/__tests__/inner_class.test.tsx, www/components/Docs/Class.tsx, www/components/Docs/Function.tsx, www/components/Docs/TypeAnnotation.tsx, www/components/Docs/Variable.tsx, www/components/SPA/SymbolPage.tsx, www/components/Sidebar/ClassContents.tsx, www/components/core/theme/theme.ts, www/components/core/typography/Code.tsx, www/lib/url.ts, www/next.config.js, www/types/emotion.d.ts
Link is displayed when a code block is hovered (only for the first occurrence in case of overloads):
=> feat: Display anchor links for class members

www/lib/test/spa.tsx, www/pages/_app.tsx, www/pages/_spa.tsx
=> chore: remove props from SPAIndex

.pre-commit-config.yaml
* #92
* #89
* #88
* __->__ #90
=> chore: make ufmt Python 3.10 aware

.pre-commit-config.yaml, py_wtf/cli/__init__.py, py_wtf/indexer/pypi.py, py_wtf/repository.py, pyproject.toml, tests/indexer/test_pypi.py, tests/test_repository.py
* #92
* #89
* __->__ #88
* #90
=> chore: asyncify downloading stuff

.pre-commit-config.yaml, py_wtf/cli/__init__.py, py_wtf/indexer/file.py, py_wtf/indexer/pypi.py, py_wtf/logging.py, py_wtf/repository.py, pyproject.toml
* #92
* __->__ #89
* #88
* #90
=> feat: index top 50 pypi packages

py_wtf/indexer/documentation.py, www/.eslintrc.json, www/__tests__/module.test.tsx, www/__tests__/myst.test.tsx, www/components/Docs/Class.tsx, www/components/Docs/Documentation.tsx, www/components/Docs/Function.tsx, www/components/Docs/Module.tsx, www/components/Docs/Project.tsx, www/components/Docs/Variable.tsx, www/components/MyST.tsx, www/lib/url.ts, www/package-lock.json, www/package.json
=> feat: render MyST

.github/workflows/frontend-tests.yml, README.md, www/package-lock.json, www/package.json
=> Explicitly upgrade to NodeJS 18

py_wtf/indexer/pypi.py, tests/indexer/test_pypi.py
This helps reduce the noise on some packages like https://py.wtf/more_itertools and https://py.wtf/pathspec
See #110
=> feat: try and index pure python wheel first

py_wtf/indexer/pypi.py
* #118
* __->__ #117
Turns out there are some circular dependencies on pypi, which makes the indexer deadlock. We'll implement some sort of automatic circular dependency detection later, but for now, add `poetry-plugin-export` on the blocklist until https://github.com/python-poetry/poetry/pull/5980 gets merged and released.
Fixes #104.
=> feat: add project blocklist

www/lib/searchDescriptor.ts, www/package-lock.json, www/package.json
* #124
* #123
* #122
* __->__ #121
=> Memoize search descriptor generation

www/components/core/Search.tsx, www/lib/searchDescriptor.ts, www/package-lock.json, www/package.json
* #124
* #123
* __->__ #122
* #121
Use `fuse.js` to fuzzy match and highlight matched characters.
=> feat: Search by fuzzy matching

www/components/core/Search.tsx, www/lib/searchDescriptor.ts, www/package-lock.json, www/package.json
feat: replace search implementation with fuzzysort
Much better results than Fuse
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zsol/py.wtf/pull/155).
* #156
* __->__ #155
=> feat: replace search implementation with fuzzysort

www/components/core/Search.tsx
search: fix results not disappearing
Fixes #158.
Also fixes a react error about missing unique keys on the highlighted texts.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zsol/py.wtf/pull/166).
* #168
* #167
* __->__ #166
=> search: fix results not disappearing

www/components/core/Search.tsx, www/package-lock.json, www/package.json
search: Add global hotkey to focus search
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zsol/py.wtf/pull/168).
* __->__ #168
* #167
=> search: Add global hotkey to focus search

.pre-commit-config.yaml, py_wtf/indexer/pypi.py, py_wtf/repository.py, pyproject.toml, requirements.txt
Support indexing dependency cycles
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zsol/py.wtf/pull/173).
* #174
* __->__ #173
=> Support indexing dependency cycles

.pre-commit-config.yaml, py_wtf/indexer/pypi.py, py_wtf/repository.py, pyproject.toml, requirements.txt
Remove blocklisted projects
Now that we can index cycles, these should be fine
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zsol/py.wtf/pull/174).
* __->__ #174
* #173
=> Remove blocklisted projects

.github/workflows/update-index.yml
Add periodic indexing workflow
=> Add periodic indexing workflow

.github/workflows/update-index.yml
=> Run the workflow manually

.github/workflows/update-index.yml, py_wtf/cli/__init__.py, py_wtf/indexer/pypi.py, py_wtf/repository.py, requirements.txt, tests/indexer/test_pypi.py, tests/test_repository.py
Incremental indexing first checks for an existing index that's already uploaded to https://py.wtf before downloading sources and indexing again.
=> Implement incremental indexing
